nyaruka/floweditor

- src/FlowDefinition.tsx
- src/components/Flow.tsx
- src/components/FlowMutator.tsx
- src/components/NodeEditor.tsx
- src/components/actions/Reply.tsx
- src/components/actions/SendMessage.tsx
- src/components/form/CheckboxElement.scss
- src/components/form/CheckboxElement.tsx
- src/components/form/FormElement.scss
- src/components/form/FormElement.tsx
- src/components/routers/SwitchRouter.tsx
- src/components/routers/Webhook.scss
- src/components/routers/Webhook.tsx
- src/services/Config.tsx
- test/FlowMutator.test.tsx
* Add CheckboxElement component
* Add option for FormElements to have a border
* Rename SendMessage to Reply
* Add all_urns option on advanced pane
* Fix bug with removing headers and cases
> Add support for all_urns on Reply

- src/components/Modal.tsx
- src/components/NodeEditor.tsx
- src/services/Config.tsx
Allows distinguishing when advanced settings are available (while translating, editing, or both)
> Advanced config

- src/components/Modal.tsx
- primary button should be farthest to the right in editor modal
> Button order

- src/components/Flow.tsx
- src/components/Node.tsx
- src/components/actions/Reply/ReplyForm.test.tsx
- src/components/actions/Reply/ReplyForm.tsx
- src/services/Localization.ts
> Localization pre population

- src/components/Simulator/Simulator.tsx
- src/components/form/TextInputElement/TextInputElement.tsx
Apparently this API is [on its way out](https://github.com/yannickcr/eslint-plugin-react/issues/678).
> remove instances of findDOMNode

- src/components/NodeEditor/NodeEditor.tsx
- src/components/routers/WebhookRouter.tsx
fixes issue whereby headers weren't displaying properly for nodes that don't already contain webhook routers
> fix headers

- src/component/form/GroupElement.test.tsx
- src/component/form/GroupElement.tsx
> close on select

- src/component/Button.scss
- src/component/Exit.scss
- src/component/Modal.scss
- src/component/Node.scss
- src/component/Node.tsx
- src/component/actions/Action/Action.scss
- src/component/index.scss
- src/global.scss
- src/services/Plumber.ts
- src/variables.scss
Things to look at:
* Roundy nodes, modals, buttons, and endpoints
* Bit more contrast for the canvas
Compare with: https://hardcore-hypatia-8b3d76.netlify.com/
I think I like this direction, thoughts?
> Experiment: Curves

- src/component/Button.scss
- src/component/Exit.scss
- src/component/Exit.tsx
- src/component/Node.scss
- src/component/Simulator/Simulator.scss
- src/component/form/TextInputElement/CharCount.scss
- src/component/form/TextInputElement/TextInputElement.scss
- src/component/index.scss
- src/component/routers/Webhook.scss
- src/component/shared.scss
- src/global.scss
- src/palette_au.scss
- src/palette_ca.scss
- src/palette_ec.scss
- src/services/Plumber.ts
- src/variables.scss
* fixes some detail issues and border intersections
* lighter still
> icier canvas, a lot less grey

- assets/flows/9ecc8e84-6b83-442b-a04a-8094d5de997b.json
- assets/flows/a4f64f1b-85bc-477e-b706-de313a022979.json
- preview/src/index.html
- src/component/Exit.scss
- src/component/Flow.tsx
- src/component/Node.scss
- src/component/Node.tsx
- src/component/index.scss
- src/component/index.tsx
- src/global.scss
- src/services/FlowMutator.ts
- src/services/Plumber.ts
- src/utils/index.ts
Snap to grid after node placement instead of on mouse move.
> Smooth drag

- assets/flows/9ecc8e84-6b83-442b-a04a-8094d5de997b.json
- assets/flows/a4f64f1b-85bc-477e-b706-de313a022979.json
- preview/src/index.html
- src/component/Exit.scss
- src/component/Node.tsx
- src/component/index.scss
- src/component/index.tsx
- src/global.scss
- src/services/FlowMutator.ts
- src/services/Plumber.ts
* Allow parent container to determine canvas size
* Honor 20 x 20 grid for movement and node placement
Fixes: #114
> Canvas updates

- package-lock.json
- package.json
- src/component/Exit.tsx
- src/component/Flow.tsx
- src/component/Node.tsx
- src/component/NodeEditor/NodeEditor.test.tsx
- src/component/Simulator/Simulator.tsx
- src/component/actions/Action/Action.tsx
- src/component/form/CaseElement.test.tsx
- src/component/form/TextInputElement/TextInputElement.tsx
- src/component/index.tsx
- src/component/routers/WebhookRouter.tsx
- src/services/FlowMutator.ts
- src/services/Plumber.ts
- src/utils/index.ts
want to make sure we preserve format across PRs. note that i ran it for this pr to clean up files that haven't yet been 'prettified'.
> Enforce prettier on commit

- src/component/Flow.tsx
- src/utils/index.ts
> Don't show editor when dragging back to the same node

- src/component/actions/ChangeGroups/AddGroupsForm.tsx
- src/component/form/FieldElement.tsx
Tweaks the help text for add group and update field. Fixes: #159
> Update field help

- src/component/NodeEditor/NodeEditor.test.tsx
- src/component/NodeEditor/NodeEditor.tsx
> show result name

- package-lock.json
- package.json
This does two things for precommit:
* Only prettifies files that have been staged
* Changes are applied as part of the active commit being attempted
> Only lint staged files on precommit

- src/component/FlowList.tsx
> fix flow list

- src/component/Node.scss
- src/component/Node.tsx
- src/component/index.scss
- src/variables.scss
* Remove box-shadow for in place nodes
* Add grey borders
> Shadows only whilst dragging

- src/component/Node.scss
- src/component/Node.tsx
- src/component/TitleBar/TitleBar.scss
- src/component/index.scss
- src/global.scss
- src/services/Plumber.ts
- src/variables.scss
> Wrap jsplumb nodes so endpoints don't overlap

- src/component/Node.scss
- src/component/Node.tsx
Move the necessary styles to the parent node container
> Fix z-index on drag

- src/store/thunks.ts
Forgot I had already made a naive reflow, but the update spec was just a bit off
> Fix update spec on reflow

- assets/config.js
- preview/src/app.tsx
properly deal w/ dev, preview configs
> two configs

- src/component/NodeEditor/NodeEditor.tsx
> Group widget now Groups widget

- src/component/Flow.tsx
- src/component/Node.tsx
- src/component/Simulator/Simulator.tsx
- src/store/__snapshots__/mutators.test.ts.snap
- src/store/__snapshots__/thunks.test.ts.snap
- src/store/__test__.ts
- src/store/thunks.test.ts
- src/store/thunks.ts
- src/testUtils/matchers.ts
- webpack/webpack.dev.js
Review after #254 
Just addresses linting errors in `Simulator.tsx`
> Simulator Linting

- assets/flows/9ecc8e84-6b83-442b-a04a-8094d5de997b.json
- assets/flows/a4f64f1b-85bc-477e-b706-de313a022979.json
- preview/src/index.html
- src/component/Flow.scss
- src/component/FlowList.scss
- src/component/FlowList.tsx
- src/component/LanguageSelector.scss
- src/component/Node.tsx
- src/component/__snapshots__/FlowList.test.ts.snap
- src/component/__snapshots__/index.test.ts.snap
- src/component/index.scss
- src/component/index.tsx
- src/global.scss
- src/services/Plumber.ts
- src/store/__snapshots__/thunks.test.ts.snap
- src/utils/index.tsx
These are just some layout tweaks to position things more realistically as if they lived inside some container to make sure that we are doing right by jsplumb and any absolute positioning within the editor.
Also, anchored flow editor coordinate space at `0, 0` instead of `GRID_SIZE, GRID_SIZE`
> Embed Tweaks

- src/component/Flow.tsx
Honor the parent offset for drag selection
> Fix selector

- __test__/colors.json
- __test__/customer_service.json
- enzymeAdapter.js
- jest.config.js
- package-lock.json
- package.json
- rafShim.js
- setup.js
- src/component/Flow.test.ts
- src/component/Flow.tsx
- src/component/Simulator/Simulator.tsx
- src/component/TitleBar/TitleBar.test.ts
- src/component/__snapshots__/Flow.test.ts.snap
- src/component/__snapshots__/SelectSearch.test.ts.snap
- src/store/helpers.ts
- src/store/thunks.ts
- src/testUtils/index.tsx
- src/utils/index.test.tsx
- src/utils/index.tsx
First pass at covering the `Flow` component.
> Flow coverage

- src/variables.scss
Variable was wrong for removal confirmation, should defer to palette
> Use palette red for removal

- src/colors_to_consider.scss
trivial, just wanted to create a space in the repo where we can 'bookmark' colors to play with when we eventually dive into the design of the editor/bring on a designer to tighten things up. perhaps there's a better place/way to do this?
> Color Considerations

- src/store/thunks.test.ts
- src/testUtils/matchers.ts
- src/testUtils/setup.ts
...so we don't have to worry about importing custom matchers/custom matcher types.
> Declare custom matcher types

- src/component/NodeEditor/NodeEditor.tsx
- src/component/SelectSearch.tsx
- src/component/actions/ChangeGroups/AddGroupsForm.test.ts
- src/component/actions/ChangeGroups/AddGroupsForm.tsx
- src/component/actions/ChangeGroups/RemoveGroupsForm.test.ts
- src/component/actions/ChangeGroups/RemoveGroupsForm.tsx
- src/component/actions/ChangeGroups/props.ts
- src/component/form/GroupsElement.test.ts
- src/component/form/GroupsElement.tsx
- src/component/form/__snapshots__/GroupsElement.test.ts.snap
- src/store/helpers.test.ts
- src/store/helpers.ts
- src/store/index.ts
- src/store/mutators.test.ts
- src/store/mutators.ts
- src/store/thunks.test.ts
- src/store/thunks.ts
The group version of the contact field work to have local record of groups managed in redux.
> Local Groups

- .gitignore
- package-lock.json
- package.json
- preview/src/app.tsx
- src/component/form/TextInputElement/helpers.test.ts
- tsconfig.json
- webpack/loaders.js
- webpack/paths.js
- webpack/plugins.js
- webpack/webpack.common.js
- webpack/webpack.config.js
- webpack/webpack.dev.js
- webpack/webpack.prev.js
- webpack/webpack.umd.js
Adds a script, `build:umd`, that outputs minified JS, CSS files to be published to NPM.
> UMD build config for NPM

- src/component/FlowList.test.ts
- src/component/FlowList.tsx
- src/component/actions/ChangeGroups/__snapshots__/AddGroupsForm.test.ts.snap
- src/component/actions/ChangeGroups/__snapshots__/RemoveGroupsForm.test.ts.snap
- src/component/actions/SetContactAttrib/__snapshots__/SetContactAttribForm.test.ts.snap
- src/component/form/FlowElement.tsx
- src/component/form/__snapshots__/AttribElement.test.tsx.snap
- src/component/form/__snapshots__/GroupsElement.test.ts.snap
- src/component/index.test.ts
- src/component/index.tsx
- src/component/routers/SubflowRouter.tsx
- src/component/routers/__snapshots__/GroupsRouter.test.tsx.snap
- src/services/AssetService.test.ts
- src/services/AssetService.ts
- src/services/__snapshots__/AssetService.test.ts.snap
- src/store/__snapshots__/thunks.test.ts.snap
- src/store/thunks.test.ts
- src/store/thunks.ts
This one straddles redux a bit. I didn't want to remove the bits that components were relying on in redux until we add redux support to the AssetService all at once.
> AssetService for flows

- src/component/actions/SetContactAttrib/SetContactAttribForm.test.ts
- src/component/actions/SetContactAttrib/SetContactAttribForm.tsx
`SetContactAttribForm` is no longer wrapped by `react-redux`.
> Update Attribute Ref in SetContactAttribForm

- src/component/Modal.test.tsx
- src/component/Modal.tsx
- src/component/NodeEditor/NodeEditor.tsx
- src/component/SelectSearch/SelectSearch.test.ts
- src/component/__snapshots__/Modal.test.tsx.snap
- src/component/form/GroupsElement.test.ts
- src/global.scss
- src/testUtils/index.tsx
Use `typeConfig.type` instead of `nodeEditor.wait.type`.
> Fix timeout control display logic

- src/component/actions/SendBroadcast/SendBroadcastForm.test.ts
- src/component/actions/SendBroadcast/SendBroadcastForm.tsx
- src/component/actions/SendBroadcast/SendBroadcastFormHelper.tsx
- src/config/typeConfigs.ts
- src/store/nodeEditor.ts
Don't let form helpers generate uuids, instead honor parent action uuid. 
@ycleptkellan you will want this for your current work
> Fix standalone broadcast

- preview/assets/flow_content/a4f64f1b-85bc-477e-b706-de313a022979.json
- src/components/__snapshots__/index.test.ts.snap
- src/components/flow/Flow.scss
- src/components/index.scss
- src/components/index.test.ts
- src/components/index.tsx
- src/components/simulator/Simulator.tsx
- src/store/helpers.ts
- src/utils/index.tsx
Adds a download button for the current flow definition for @rowanseymour
> Download button

- preview/assets/flow_content/a4f64f1b-85bc-477e-b706-de313a022979.json
- preview/src/index.html
- src/components/flow/routers/groups/__snapshots__/GroupsRouterForm.test.ts.snap
- src/components/flow/routers/webhook/WebhookRouterForm.scss
- src/components/flow/routers/webhook/WebhookRouterForm.test.ts
- src/components/flow/routers/webhook/WebhookRouterForm.tsx
- src/components/flow/routers/webhook/__snapshots__/WebhookRouterForm.test.ts.snap
- src/components/flow/routers/webhook/header/HeaderElement.test.ts
- src/components/flow/routers/webhook/header/HeaderElement.tsx
- src/components/flow/routers/webhook/header/__snapshots__/HeaderElement.test.ts.snap
- src/components/flow/routers/webhook/helpers.ts
- src/components/nodeeditor/constants.ts
- src/components/simulator/Simulator.scss
- src/components/sticky/Sticky.scss
- src/config/operatorConfigs.ts
- src/global.scss
- src/store/nodeEditor.ts
- src/testUtils/assetCreators.ts
> Webhook GET

- src/components/flow/Flow.test.ts
- src/components/flow/actions/addlabels/AddLabelsForm.test.ts
- src/components/flow/actions/addlabels/__snapshots__/AddLabelsForm.test.ts.snap
- src/components/flow/actions/changegroups/addgroups/AddGroupsForm.test.ts
- src/components/flow/actions/changegroups/addgroups/__snapshots__/AddGroupsForm.test.ts.snap
- src/components/flow/actions/changegroups/removegroups/RemoveGroupsForm.test.ts
- src/components/flow/actions/changegroups/removegroups/__snapshots__/RemoveGroupsForm.test.ts.snap
- src/components/flow/actions/localization/MsgLocalizationForm.test.ts
- src/components/flow/actions/sendbroadcast/SendBroadcastForm.test.ts
- src/components/flow/actions/sendemail/SendEmailForm.test.ts
- src/components/flow/actions/sendmsg/SendMsgForm.test.ts
- src/components/flow/actions/setrunresult/SetRunResultForm.test.ts
- src/components/flow/actions/startsession/StartSessionForm.test.ts
- src/components/flow/actions/updatecontact/UpdateContactForm.test.ts
- src/components/flow/routers/expression/ExpressionRouterForm.test.ts
- src/components/flow/routers/expression/__snapshots__/ExpressionRouterForm.test.ts.snap
- src/components/flow/routers/localization/RouterLocalizationForm.test.ts
- src/components/flow/routers/response/ResponseRouterForm.test.ts
- src/components/flow/routers/response/__snapshots__/ResponseRouterForm.test.ts.snap
- src/components/flow/routers/webhook/WebhookRouterForm.test.ts
- src/components/flow/routers/webhook/WebhookRouterForm.tsx
- src/components/flow/routers/webhook/__snapshots__/WebhookRouterForm.test.ts.snap
- src/components/flow/routers/webhook/header/HeaderElement.test.ts
- src/components/flow/routers/webhook/header/HeaderElement.tsx
- src/components/flow/routers/webhook/header/__snapshots__/HeaderElement.test.ts.snap
- src/components/flow/routers/webhook/helpers.ts
- src/testUtils/matchers.ts
- src/testUtils/setup.ts
* Add custom matcher for call argument snapshots
> Webhook tests

- preview/assets/flow_content/a4f64f1b-85bc-477e-b706-de313a022979.json
- src/components/dialog/Dialog.tsx
- src/components/flow/Flow.test.ts
- src/components/flow/Flow.tsx
- src/components/flow/__snapshots__/Flow.test.ts.snap
- src/components/flow/node/Node.tsx
- src/components/flow/routers/caselist/CaseList.test.ts
- src/components/flow/routers/expression/helpers.ts
- src/components/helpers.ts
- src/components/nodeeditor/NodeEditor.tsx
- src/store/__snapshots__/thunks.test.ts.snap
- src/store/actionTypes.ts
- src/store/editor.ts
- src/store/flowContext.ts
- src/store/helpers.test.ts
- src/store/helpers.ts
- src/store/thunks.test.ts
- src/store/thunks.ts
TODO: See if we can use inboundConnections on ghostNode to simplify this further.
> Properly clear pending connections

- src/store/__snapshots__/thunks.test.ts.snap
- src/store/mutators.ts
- src/store/thunks.test.ts
* ensure new node uuid is created when switching from a router to an action
> Type switch UUID fix

- src/store/__snapshots__/thunks.test.ts.snap
- src/store/helpers.ts
- src/store/mutators.test.ts
- src/store/mutators.ts
- src/store/thunks.test.ts
- src/store/thunks.ts
> Cleanup up pointers on node removal

- preview/config.js
- src/components/flow/routers/result/helpers.ts
- src/components/form/assetselector/AssetSelector.tsx
- src/external/index.ts
- src/store/thunks.ts
* Also tweaks recipients url for RP
> Find assets for unnamed initial values

- __test__/assets/recipients.json
- preview/assets/recipients.json
- src/components/flow/routers/field/FieldRouterForm.test.ts
- src/components/flow/routers/field/__snapshots__/FieldRouterForm.test.ts.snap
- src/components/flow/routers/field/helpers.ts
- src/components/flow/routers/helpers.ts
- src/components/flow/routers/result/helpers.ts
- src/components/form/assetselector/AssetSelector.tsx
* Also initializes unnamed values in the AssetSelector on remote load if needed
> Nested operand in configs

- src/components/flow/actions/action/Action.scss
- src/components/flow/actions/addlabels/AddLabelsForm.tsx
- src/components/flow/actions/addlabels/helpers.ts
- src/components/flow/actions/transferairtime/TransferAirtime.scss
- src/components/flow/actions/transferairtime/TransferAirtime.test.ts
- src/components/flow/actions/transferairtime/TransferAirtime.tsx
- src/components/flow/actions/transferairtime/__snapshots__/TransferAirtime.test.ts.snap
- src/components/flow/routers/airtime/AirtimeRouterForm.test.ts
- src/components/flow/routers/airtime/AirtimeRouterForm.tsx
- src/components/flow/routers/airtime/__snapshots__/AirtimeRouterForm.test.ts.snap
- src/components/flow/routers/airtime/currency/CurrencyElement.scss
- src/components/flow/routers/airtime/currency/CurrencyElement.tsx
- src/components/flow/routers/airtime/helpers.ts
- src/components/flow/routers/resthook/ResthookRouterForm.tsx
- src/components/form/ValidationFailures.scss
- src/components/form/ValidationFailures.tsx
- src/components/form/assetselector/AssetSelector.tsx
- src/components/form/assetselector/helpers.ts
- src/components/shared.scss
- src/config/__snapshots__/typeConfigs.test.ts.snap
- src/config/typeConfigs.ts
- src/external/index.ts
- src/flowTypes.ts
- src/store/currencies.ts
- src/store/flowContext.ts
- src/store/thunks.ts
- src/testUtils/assetCreators.ts
> Add airtime transfer form

- preview/assets/flow_content/a4f64f1b-85bc-477e-b706-de313a022979.json
- src/components/canvas/Canvas.tsx
- src/components/canvas/CanvasDraggable.tsx
- src/components/canvas/helpers.ts
- src/components/flow/Flow.tsx
- src/components/flow/__snapshots__/Flow.test.ts.snap
- src/components/flow/node/Node.tsx
- src/components/sticky/Sticky.test.ts
- src/components/sticky/Sticky.tsx
- src/services/Plumber.ts
- src/store/__snapshots__/thunks.test.ts.snap
- src/store/editor.ts
- src/store/helpers.ts
- src/utils/index.tsx
- Position and collision detection within canvas
> Move more dnd bits under canvas control

- src/components/flow/actions/updatecontact/UpdateContactForm.tsx
- src/components/flow/props.ts
- src/components/flow/routers/airtime/AirtimeRouterForm.tsx
- src/components/flow/routers/field/FieldRouterForm.tsx
- src/components/flow/routers/groups/GroupsRouterForm.tsx
- src/components/flow/routers/resthook/ResthookRouterForm.tsx
- src/components/flow/routers/result/ResultRouterForm.tsx
- src/components/flow/routers/subflow/SubflowRouterForm.tsx
- src/testUtils/assetCreators.ts
Fixes #402 
Fixes #404 
Fixes #405 
Fixes #406
> Fix asset props for splits

- .travis.yml
- __test__/config.js
- preview/assets/flow_content/a4f64f1b-85bc-477e-b706-de313a022979.json
- preview/config.js
- preview/src/index.html
- src/components/canvas/Canvas.scss
- src/components/canvas/Canvas.test.tsx
- src/components/canvas/Canvas.tsx
- src/components/canvas/__snapshots__/Canvas.test.tsx.snap
- src/components/index.tsx
- src/config/ConfigProvider.tsx
- src/flowTypes.ts
- src/testUtils/index.tsx
- webpack/webpack.dev.js
- webpack/webpack.prev.js
- webpack/webpack.umd.js
- wrapper/src/index.tsx
* Publish global wrapper function to allow easy non-react embeds
* Add tests for canvas
* Fix canvas growth for migrated flows without dimensions
* Fix race condition with canvas state changes
> Prep for RP embed

- src/components/canvas/Canvas.test.tsx
- src/components/form/FormElement.scss
- src/components/form/assetselector/AssetSelector.scss
- src/components/form/assetselector/AssetSelector.tsx
- src/components/form/textinput/TextInputElement.scss
- wrapper/src/index.tsx
> Updates for embedding

- src/components/canvas/Canvas.test.tsx
- src/components/canvas/Canvas.tsx
- src/components/canvas/__snapshots__/Canvas.test.tsx.snap
- src/components/canvas/helpers.ts
> Add reflow to canvas

- src/components/canvas/Canvas.test.tsx
- src/components/canvas/Canvas.tsx
- src/components/canvas/helpers.ts
- src/components/flow/Flow.test.ts
- src/components/flow/Flow.tsx
- src/components/flow/__snapshots__/Flow.test.ts.snap
- src/store/helpers.ts
- src/store/thunks.ts
Ensure that position changes on the canvas find their way to our store
> Propagate position changes

- lambda-src/groups.js
- lambda-src/utils/index.js
- package-lock.json
- package.json
- preview/config.js
- src/components/flow/actions/addlabels/AddLabelsForm.tsx
- src/components/flow/actions/addlabels/__snapshots__/AddLabelsForm.test.ts.snap
- src/components/flow/actions/changegroups/addgroups/AddGroupsForm.tsx
- src/components/flow/actions/changegroups/addgroups/__snapshots__/AddGroupsForm.test.ts.snap
- src/components/flow/actions/changegroups/helpers.test.ts
- src/components/flow/actions/changegroups/helpers.ts
- src/components/flow/actions/updatecontact/UpdateContactForm.tsx
- src/components/flow/actions/updatecontact/__snapshots__/UpdateContactForm.test.ts.snap
- src/components/flow/props.ts
- src/components/flow/routers/airtime/currency/CurrencyElement.tsx
- src/components/flow/routers/caselist/__snapshots__/CaseList.test.ts.snap
- src/components/form/assetselector/AssetSelector.scss
- src/components/form/assetselector/AssetSelector.tsx
- src/components/nodeeditor/NodeEditor.tsx
- src/components/nodeeditor/TypeList.tsx
- src/components/simulator/Simulator.scss
- src/components/simulator/Simulator.tsx
- src/components/simulator/__snapshots__/Simulator.test.ts.snap
- src/external/index.ts
- src/flowTypes.ts
- src/store/thunks.ts
- src/testUtils/assetCreators.ts
- src/utils/reactselect.ts
- src/variables.scss
- webpack/webpack.dev.js
* Use RP groups api endpoint to fetch / create groups
* Honor CSRF cookie as http header
* Fancy styling to make creation errors appear embedded within the control
* Filter out dynamic groups from add/remove group actions
> Create groups on the fly, switch to API v2

- lambda-src/groups.js
- lambda-src/labels.js
- preview/config.js
- src/components/flow/actions/addlabels/AddLabelsForm.tsx
- src/components/flow/actions/addlabels/__snapshots__/AddLabelsForm.test.ts.snap
- src/external/index.ts
> Create labels on the fly, move to api v2

- lambda-src/fields.js
- preview/config.js
- src/components/flow/actions/updatecontact/UpdateContactForm.tsx
- src/components/flow/actions/updatecontact/__snapshots__/UpdateContactForm.test.ts.snap
- src/components/flow/actions/updatecontact/__snapshots__/helpers.test.ts.snap
- src/components/flow/actions/updatecontact/helpers.ts
- src/components/form/assetselector/AssetSelector.tsx
- src/components/form/assetselector/helpers.ts
- src/external/index.ts
> Create fields on the fly, move to api v2

- src/components/flow/node/Node.tsx
- src/components/flow/routers/field/FieldRouterForm.tsx
- src/components/flow/routers/field/__snapshots__/FieldRouterForm.test.ts.snap
- src/components/flow/routers/field/helpers.ts
- src/components/flow/routers/result/ResultRouterForm.tsx
- src/components/flow/routers/result/helpers.ts
- src/store/flowContext.ts
- src/store/helpers.ts
- src/store/mutators.ts
- src/store/thunks.test.ts
- src/store/thunks.ts
> Track references for flow results, mark invalid routers

- src/components/simulator/LogEvent.tsx
- src/components/simulator/Simulator.scss
- src/components/simulator/Simulator.tsx
- src/components/simulator/__snapshots__/Simulator.test.ts.snap
- src/components/simulator/helpers.ts
Adds quick replies to the simulator and as a side effect now supports arbitrary drawer sizes.
Fixes: #458
> Add quick replies to simulator

- src/components/canvas/Canvas.tsx
- src/components/flow/node/Node.tsx
- src/components/simulator/Simulator.tsx
> Snap to grid on drop

- src/components/canvas/Canvas.tsx
- src/components/canvas/CanvasDraggable.scss
- src/components/canvas/CanvasDraggable.tsx
- src/components/flow/Flow.tsx
- src/components/flow/node/Node.scss
- src/components/sticky/Sticky.scss
- src/global.scss
- src/services/Plumber.ts
- src/store/thunks.ts
- src/variables.scss
* Add/Remove positions for created or removed nodes in canvas
* Fix styling for notes titles when embedding
* Add transition for snapping
* Bolden plumbing lines
Fixes: #456 #462
> Issues with notes

- src/components/flow/actions/addurn/AddURNForm.scss
- src/components/flow/actions/sendmsg/SendMsgForm.scss
- src/components/flow/actions/sendmsg/__snapshots__/SendMsgForm.test.ts.snap
- src/components/flow/routers/airtime/currency/CurrencyElement.scss
- src/components/flow/routers/case/CaseElement.tsx
- src/components/flow/routers/case/__snapshots__/CaseElement.test.tsx.snap
- src/components/flow/routers/caselist/__snapshots__/CaseList.test.ts.snap
- src/components/flow/routers/field/FieldRouterForm.tsx
- src/components/flow/routers/field/__snapshots__/FieldRouterForm.test.ts.snap
- src/components/flow/routers/result/ResultRouterForm.tsx
- src/components/form/timeout/__snapshots__/TimeoutControl.test.ts.snap
- src/components/index.scss
- src/components/languageselector/__snapshots__/LanguageSelector.test.ts.snap
- src/global.scss
- src/services/Plumber.ts
- src/utils/index.test.tsx
- src/utils/index.tsx
- src/utils/reactselect.ts
> Fix react select styling on embed

- preview/config.js
- src/components/sticky/Sticky.scss
- src/store/mutators.test.ts
- src/store/mutators.ts
- src/store/thunks.test.ts
- src/store/thunks.ts
- webpack/webpack.dev.js
> Use bounds only in canvas

- src/components/flow/routers/case/CaseElement.scss
- src/components/flow/routers/case/CaseElement.tsx
- src/components/flow/routers/case/helpers.test.ts
- src/components/flow/routers/case/helpers.ts
- src/components/flow/routers/digits/__snapshots__/DigitsRouterForm.test.ts.snap
- src/components/flow/routers/digits/helpers.ts
- src/components/flow/routers/expression/__snapshots__/ExpressionRouterForm.test.ts.snap
- src/components/flow/routers/expression/helpers.ts
- src/components/flow/routers/field/__snapshots__/FieldRouterForm.test.ts.snap
- src/components/flow/routers/field/helpers.ts
- src/components/flow/routers/groups/__snapshots__/GroupsRouterForm.test.ts.snap
- src/components/flow/routers/groups/helpers.ts
- src/components/flow/routers/helpers.ts
- src/components/flow/routers/menu/helpers.ts
- src/components/flow/routers/response/ResponseRouterForm.test.ts
- src/components/flow/routers/response/__snapshots__/ResponseRouterForm.test.ts.snap
- src/components/flow/routers/response/helpers.ts
- src/components/flow/routers/result/helpers.ts
- src/components/flow/routers/wait/helpers.ts
- src/flowTypes.ts
- src/store/__snapshots__/validators.test.ts.snap
- src/store/thunks.ts
- src/store/validators.test.ts
- src/store/validators.ts
> Add support for relative date cases

- src/components/simulator/Simulator.scss
- src/components/simulator/Simulator.tsx
> Add simulation keypad drawer

- src/components/flow/actions/addurn/AddURNForm.tsx
- src/components/flow/routers/field/__snapshots__/FieldRouterForm.test.ts.snap
- src/config/typeConfigs.ts
> Only use twitterid scheme for AddURN

- __test__/assets/flows/a4f64f1b-85bc-477e-b706-de313a022979.json
- __test__/flows/colors.json
- src/components/flow/actions/action/Action.scss
- src/components/flow/actions/action/__snapshots__/Action.test.ts.snap
- src/components/flow/actions/playaudio/__snapshots__/PlayAudioForm.test.ts.snap
- src/components/flow/routers/airtime/__snapshots__/AirtimeRouterForm.test.ts.snap
- src/components/flow/routers/case/__snapshots__/CaseElement.test.tsx.snap
- src/components/flow/routers/case/__snapshots__/helpers.test.ts.snap
- src/components/flow/routers/caselist/__snapshots__/CaseList.test.ts.snap
- src/components/flow/routers/digits/__snapshots__/DigitsRouterForm.test.ts.snap
- src/components/flow/routers/expression/__snapshots__/ExpressionRouterForm.test.ts.snap
- src/components/flow/routers/field/__snapshots__/FieldRouterForm.test.ts.snap
- src/components/flow/routers/helpers.ts
- src/components/flow/routers/menu/__snapshots__/MenuRouterForm.test.ts.snap
- src/components/flow/routers/response/__snapshots__/ResponseRouterForm.test.ts.snap
- src/components/flow/routers/resthook/__snapshots__/ResthookRouterForm.test.ts.snap
- src/components/flow/routers/subflow/SubflowRouterForm.tsx
- src/components/flow/routers/subflow/__snapshots__/SubflowRouterForm.test.ts.snap
- src/components/flow/routers/subflow/helpers.ts
- src/components/flow/routers/wait/__snapshots__/WaitRouterForm.test.ts.snap
- src/components/flow/routers/webhook/__snapshots__/WebhookRouterForm.test.ts.snap
- src/components/form/assetselector/AssetSelector.tsx
- src/components/shared.scss
- src/config/__snapshots__/operatorConfigs.test.ts.snap
- src/config/__snapshots__/typeConfigs.test.ts.snap
- src/config/interfaces.ts
- src/config/typeConfigs.ts
- src/store/__snapshots__/thunks.test.ts.snap
- src/testUtils/assetCreators.ts
> Only show same type flows for subflow router

- src/components/canvas/Canvas.test.tsx
- src/components/canvas/Canvas.tsx
- src/components/canvas/helpers.ts
- src/components/flow/Flow.tsx
- src/components/flow/exit/Exit.scss
- src/components/flow/node/Node.scss
- src/components/sticky/Sticky.test.ts
- src/components/sticky/Sticky.tsx
- src/variables.scss
* Also better behavior for clicking on new note titles / bodies
> Slightly better reflow logic

- src/components/flow/actions/sendbroadcast/SendBroadcastForm.test.ts
- src/components/flow/actions/sendbroadcast/__snapshots__/SendBroadcastForm.test.ts.snap
- src/components/flow/actions/startsession/StartSessionForm.test.ts
- src/components/flow/actions/startsession/__snapshots__/StartSessionForm.test.ts.snap
- src/components/flow/routers/random/RandomRouterForm.test.ts
- src/components/flow/routers/random/RandomRouterForm.tsx
- src/components/flow/routers/random/__snapshots__/RandomRouterForm.test.ts.snap
- src/components/flow/routers/random/helpers.ts
- src/components/flow/routers/result/ResultRouterForm.test.ts
- src/components/flow/routers/result/__snapshots__/ResultRouterForm.test.ts.snap
- src/components/flow/routers/subflow/__snapshots__/SubflowRouterForm.test.ts.snap
- src/components/form/FormElement.scss
- src/components/nodeeditor/NodeEditor.tsx
- src/store/__snapshots__/thunks.test.ts.snap
- src/store/thunks.test.ts
- src/store/thunks.ts
- src/testUtils/assetCreators.ts
> Fix adding random using plus button

- src/components/__snapshots__/index.test.ts.snap
- src/components/flow/Flow.test.ts
- src/components/flow/Flow.tsx
- src/components/flow/actions/action/Action.test.ts
- src/components/flow/actions/action/Action.tsx
- src/components/flow/actions/localization/MsgLocalizationForm.tsx
- src/components/flow/actions/saymsg/SayMsgForm.tsx
- src/components/flow/actions/sendmsg/SendMsgForm.tsx
- src/components/flow/routers/caselist/CaseList.tsx
- src/components/index.tsx
- src/components/simulator/Simulator.tsx
- src/config/ConfigProvider.test.tsx
- src/config/ConfigProvider.tsx
- src/config/__snapshots__/ConfigProvider.test.tsx.snap
- src/flowTypes.ts
- src/global.scss
- src/store/thunks.ts
- src/testUtils/index.tsx
* Update config context to be uniform
* onLoad callback
> Embed callbacks

- src/store/__snapshots__/thunks.test.ts.snap
- src/store/mutators.ts
- src/store/thunks.test.ts
- src/store/thunks.ts
* Switch from router to action
* Add test
> Fix switching from router to action

- src/components/flow/Flow.scss
- src/components/flow/Flow.test.ts
- src/components/flow/Flow.tsx
- src/components/flow/__snapshots__/Flow.test.ts.snap
- src/store/helpers.test.ts
- src/store/helpers.ts
- src/store/thunks.test.ts
- src/store/thunks.ts
* Empty node message and button
* Remove ensureStartNode
> Add empty flow treatment

- src/components/dialog/Dialog.tsx
- src/components/form/textinput/TextInputElement.test.ts
- src/components/form/textinput/__snapshots__/helpers.test.ts.snap
- src/components/form/textinput/functions.json
- src/components/index.scss
- src/components/index.test.ts
- src/components/index.tsx
- src/components/languageselector/LanguageSelector.tsx
- src/components/loading/Loading.scss
- src/components/loading/Loading.tsx
- src/components/nodeeditor/NodeEditor.scss
- src/components/shared.scss
- src/store/editor.ts
- src/store/mutators.ts
- src/store/thunks.ts
- src/variables.scss
* Dialog to show alerts on save failures
* Loading animation component to show pending saves
> Saving feedback

- src/store/thunks.ts
> Don't trample slow revision creation

- src/components/flow/actions/sendmsg/SendMsgForm.tsx
- src/components/flow/actions/updatecontact/UpdateContactForm.tsx
- src/components/flow/actions/updatecontact/__snapshots__/UpdateContactForm.test.ts.snap
- src/components/flow/routers/case/__snapshots__/CaseElement.test.tsx.snap
- src/components/flow/routers/case/__snapshots__/helpers.test.ts.snap
- src/components/flow/routers/caselist/__snapshots__/CaseList.test.ts.snap
- src/components/flow/routers/response/__snapshots__/ResponseRouterForm.test.ts.snap
- src/components/flow/routers/wait/__snapshots__/WaitRouterForm.test.ts.snap
- src/components/form/assetselector/AssetSelector.tsx
- src/config/__snapshots__/operatorConfigs.test.ts.snap
- src/config/__snapshots__/typeConfigs.test.ts.snap
- src/config/interfaces.ts
- src/store/__snapshots__/thunks.test.ts.snap
> Update flow types to fix filtering, add formClearable to AssetSelector

- __test__/flows/boring.json
- src/store/__snapshots__/helpers.test.ts.snap
- src/store/__snapshots__/mutators.test.ts.snap
- src/store/__snapshots__/thunks.test.ts.snap
- src/store/helpers.test.ts
- src/store/helpers.ts
- src/store/mutators.test.ts
- src/store/mutators.ts
- src/store/thunks.test.ts
> Fix fetching run results on load

- src/components/flow/actions/localization/MsgLocalizationForm.tsx
- src/components/flow/actions/localization/__snapshots__/MsgLocalizationForm.test.ts.snap
- src/components/flow/actions/sendmsg/SendMsgForm.tsx
- src/components/flow/actions/sendmsg/__snapshots__/SendMsgForm.test.ts.snap
- src/components/flow/actions/sendmsg/helpers.ts
- src/components/form/multichoice/MultiChoice.test.tsx
- src/components/form/multichoice/MultiChoice.tsx
- src/components/form/multichoice/__snapshots__/MultiChoice.test.tsx.snap
- src/components/simulator/Simulator.tsx
- src/store/validators.ts
* Reset quick replies after each sprint
* Confirm non-empty new entries
> Quick Reply updates

- src/components/flow/node/Node.scss
- src/components/flow/node/Node.tsx
- src/components/flow/node/helpers.ts
- src/components/flow/routers/airtime/AirtimeRouterForm.scss
- src/components/flow/routers/airtime/AirtimeRouterForm.tsx
- src/components/flow/routers/airtime/__snapshots__/AirtimeRouterForm.test.ts.snap
- src/components/flow/routers/resthook/ResthookRouter.scss
- src/components/flow/routers/resthook/ResthookRouterForm.tsx
- src/components/flow/routers/resthook/__snapshots__/ResthookRouterForm.test.ts.snap
- src/components/form/select/tags/TaggingElement.tsx
- src/components/shared.scss
- src/palette_ec.scss
- src/services/Plumber.ts
- src/store/helpers.ts
- src/store/mutators.ts
- src/store/thunks.ts
* Show result names on webhook, resthook, and airtime splits
* Keep asset store up to date for these results
> Honor result names for webhook based actions

- src/components/canvas/Canvas.test.tsx
- src/components/canvas/Canvas.tsx
- src/components/canvas/__snapshots__/Canvas.test.tsx.snap
- src/components/flow/Flow.tsx
- src/components/form/assetselector/AssetSelector.tsx
- src/components/form/textinput/TextInputElement.test.ts
- src/components/form/textinput/__snapshots__/TextInputElement.test.ts.snap
- src/components/form/textinput/__snapshots__/helpers.test.ts.snap
- src/utils/completion.ts
* Dragging new nodes will expand the canvas as needed and scroll the window
* Adjust base canvas height to be base on window height
* Bonus! Add contact.uuid to completion
> Drag scroll

- src/components/simulator/LogEvent.scss
- src/components/simulator/LogEvent.tsx
- src/components/simulator/Simulator.tsx
* Out of flow messages with proper exits
* Missing renders
* Clickable email details
Fixes: #514
> Sim updates

- src/components/flow/routers/case/__snapshots__/helpers.test.ts.snap
- src/components/flow/routers/case/helpers.test.ts
- src/components/flow/routers/case/helpers.ts
- src/components/flow/routers/helpers.ts
- src/config/__snapshots__/operatorConfigs.test.ts.snap
- src/config/interfaces.ts
- src/config/operatorConfigs.ts
> Audit operators, add has_time

- src/components/flow/actions/sendmsg/SendMsgForm.scss
- src/components/flow/actions/sendmsg/SendMsgForm.tsx
Fixes: #574 
Also fixes alignment issues for attachments
> Don't allow empty send messages

- src/components/flow/Flow.tsx
- src/components/flow/routers/webhook/__snapshots__/WebhookRouterForm.test.ts.snap
- src/components/flow/routers/webhook/helpers.ts
> Add default content type for webhooks

- src/components/canvas/Canvas.test.tsx
- src/components/canvas/Canvas.tsx
- src/components/flow/Flow.test.ts
- src/components/flow/Flow.tsx
- src/components/sticky/Sticky.test.ts
- src/components/sticky/Sticky.tsx
- src/store/thunks.ts
> Allow deletion of multiple nodes at once

- src/components/flow/actions/sendbroadcast/SendBroadcast.scss
- src/components/flow/actions/sendbroadcast/SendBroadcast.tsx
- src/components/flow/actions/sendbroadcast/__snapshots__/SendBroadcast.test.ts.snap
- src/components/flow/actions/sendmsg/SendMsg.scss
- src/components/flow/actions/sendmsg/SendMsg.tsx
- src/components/flow/actions/sendmsg/__snapshots__/SendMsg.test.ts.snap
> Show linebreaks for send message and send broadcast

- src/components/flow/actions/sendbroadcast/SendBroadcast.tsx
- src/components/flow/actions/sendbroadcast/SendBroadcastForm.tsx
- src/components/flow/actions/sendmsg/SendMsg.tsx
- src/components/flow/actions/sendmsg/__snapshots__/SendMsg.test.ts.snap
- src/components/form/assetselector/AssetSelector.tsx
- src/utils/reactselect.ts
> Show error styling for asset selector

- src/components/flow/exit/Exit.module.scss
- src/components/flow/exit/Exit.tsx
- src/components/flow/exit/__snapshots__/Exit.test.ts.snap
- src/external/index.ts
* Make sure recents don't take focus
* Nicer loading treatment
* No recent messages treatment
Fixes: #593
> Recent Messages

- src/components/simulator/Simulator.tsx
Fixes #602. Still trying to figure out how to test this...
> 🚑 Fix rendering of recent messages when using simulator

- src/components/flow/routers/field/helpers.ts
> ⛑️ Fix splitting by contact URN

- src/external/index.ts
> Auto page through asset results

- src/store/__snapshots__/thunks.test.ts.snap
- src/store/helpers.test.ts
- src/store/helpers.ts
- src/store/mutators.ts
- src/store/thunks.test.ts
- src/store/thunks.ts
- src/testUtils/assetCreators.ts
> Make a best effort loading non-editor flows

- src/components/flow/actions/sendemail/__snapshots__/SendEmailForm.test.ts.snap
- src/components/flow/actions/startsession/__snapshots__/StartSessionForm.test.ts.snap
- src/components/flow/actions/updatecontact/UpdateContactForm.tsx
- src/components/flow/actions/updatecontact/helpers.test.ts
- src/components/flow/routers/field/FieldRouterForm.tsx
- src/components/flow/routers/field/helpers.ts
- src/components/flow/routers/resthook/__snapshots__/ResthookRouterForm.test.ts.snap
- src/components/flow/routers/webhook/__snapshots__/WebhookRouterForm.test.ts.snap
- src/components/helpers.ts
- src/components/index.module.scss
- src/config/ConfigProvider.tsx
- src/config/__snapshots__/typeConfigs.test.ts.snap
- src/config/helpers.ts
- src/config/typeConfigs.ts
> Surveyor visibility

- package.json
- src/store/validators.test.ts
- src/store/validators.ts
- src/untyped.d.ts
- yarn.lock
> Add RFC-based header name validation

- src/components/flow/actions/sendemail/SendEmailForm.tsx
- src/components/flow/actions/sendemail/__snapshots__/SendEmailForm.test.ts.snap
- src/components/form/select/tags/TaggingElement.tsx
- src/utils/index.test.tsx
- src/utils/index.tsx
- src/utils/reactselect.ts
> Allow expressions in email recipients

- src/components/flow/actions/sendmsg/SendMsgForm.module.scss
> Tweak alignment on attachments

- src/utils/completion.ts
> Update completion for @run.results

- src/components/__snapshots__/index.test.ts.snap
- src/components/index.tsx
- src/flowTypes.ts
- src/store/thunks.ts
Used to create a revision after manual migration
> Force save flag

- src/components/form/assetselector/AssetSelector.tsx
> Show error messages during async field creation

- src/components/flow/node/Node.tsx
- src/components/flow/routers/wait/__snapshots__/WaitRouterForm.test.ts.snap
- src/config/__snapshots__/typeConfigs.test.ts.snap
- src/config/typeConfigs.ts
* Adds wait for audio for IVR
* Defers to config names on node titles for routers
Fixes: #661
> Include wait for audio on IVR

- src/components/flow/routers/result/ResultRouterForm.module.scss
- src/components/flow/routers/result/ResultRouterForm.tsx
> Use flexbox for split by result delimited

- src/components/flow/actions/action/Action.module.scss
- src/components/shared.module.scss
- src/variables.module.scss
> Fix rendering on overview for flows with long names

- src/components/form/textinput/__snapshots__/helpers.test.ts.snap
- src/utils/completion.ts
> Add external_id to completion

- src/components/canvas/CanvasDraggable.tsx
- src/components/sticky/Sticky.module.scss
> Allow text selection inside stickies

- src/components/flow/routers/groups/__snapshots__/GroupsRouterForm.test.ts.snap
- src/components/flow/routers/groups/helpers.ts
> Add name to argument list of has_group test

- src/components/flow/routers/result/ResultRouterForm.test.tsx
- src/components/flow/routers/result/__snapshots__/ResultRouterForm.test.tsx.snap
- src/components/flow/routers/result/helpers.ts
> Fix operand for non-delimited run result split

- src/store/mutators.test.ts
- src/store/mutators.ts
> Fix results erroneously adding to store

- src/components/flow/routers/case/CaseElement.module.scss
- src/components/flow/routers/case/CaseElement.tsx
- src/components/flow/routers/case/__snapshots__/CaseElement.test.tsx.snap
- src/components/flow/routers/case/__snapshots__/helpers.test.ts.snap
- src/components/flow/routers/case/helpers.ts
- src/components/flow/routers/caselist/__snapshots__/CaseList.test.tsx.snap
- src/components/flow/routers/result/__snapshots__/ResultRouterForm.test.tsx.snap
- src/config/__snapshots__/operatorConfigs.test.ts.snap
- src/config/operatorConfigs.ts
> Add location rules

- src/components/simulator/Simulator.module.scss
> Remove screen bg on simulator

- src/components/simulator/LogEvent.tsx
> Show failures in simulator

- public/index.html
- src/components/canvas/Canvas.tsx
- src/components/flow/Flow.tsx
- src/components/flow/actions/action/Action.module.scss
- src/components/flow/actions/action/Action.tsx
- src/components/flow/exit/Exit.tsx
- src/components/flow/node/Node.module.scss
- src/components/flow/node/Node.tsx
- src/components/titlebar/TitleBar.tsx
- src/external/index.ts
- src/flowTypes.ts
- src/store/thunks.ts
- src/test/config.ts
Expectation is that this is cosmetic, endpoints themselves should be gated against POSTs as necessary.
> Add mutable flag and honor it where appropriate

- codecov.yml
- src/components/flow/routers/wait/WaitRouterForm.test.tsx
- src/components/flow/routers/wait/__snapshots__/WaitRouterForm.test.tsx.snap
- src/components/flow/routers/wait/helpers.ts
- src/components/nodeeditor/constants.ts
- src/test/utils.tsx
> Use @input.attachments as operand for media hint waits

- src/components/flow/actions/playaudio/PlayAudioForm.tsx
- src/components/flow/actions/playaudio/__snapshots__/PlayAudioForm.test.ts.snap
> Tweak help text on play recording

- src/components/flow/routers/result/ResultRouterForm.test.tsx
- src/components/flow/routers/result/__snapshots__/ResultRouterForm.test.tsx.snap
- src/components/flow/routers/result/helpers.ts
> Zero based fields on delimited splits

- src/components/flow/exit/Exit.tsx
Fixes: #711 
Well, this is a really easy fix, but a huge lift to test. We don't have a top level style interaction test at the browser level, which we'd need to do this right -- punting on that for now.
> Honor upstream drag helper prop in exit state

- src/components/form/timeout/TimeoutControl.tsx
- src/components/form/timeout/__snapshots__/TimeoutControl.test.ts.snap
> Fix timeout plural for one day

- src/components/flow/actions/updatecontact/UpdateContactForm.test.ts
- src/components/flow/actions/updatecontact/UpdateContactForm.test.tsx
- src/components/flow/actions/updatecontact/__snapshots__/UpdateContactForm.test.ts.snap
- src/components/flow/actions/updatecontact/__snapshots__/UpdateContactForm.test.tsx.snap
- src/components/form/assetselector/AssetSelector.tsx
> Don't blow up typing @ on non-completion asset selectors

- src/components/simulator/Simulator.test.ts
- src/components/simulator/Simulator.tsx
> Use the displayed language when starting a simulation

- src/components/simulator/LogEvent.module.scss
- src/components/simulator/LogEvent.tsx
* Support http_logs array when viewing results that have them
* Add intent/entity table for result change events if they exist in extra
Fixes #727
> Better simulation for classification

- src/external/external.test.ts
- src/external/index.ts
> Convert flow types from the api to goflowy types

- src/components/flow/routers/airtime/currency/CurrencyElement.tsx
- src/components/simulator/LogEvent.tsx
- src/external/index.ts
- src/utils/index.tsx
- src/utils/reactselect.ts
* Add simulation event logs for airtime
* Fix styling on currency selection, add proper placeholder text
* Allow asset id to match for currency and language (eg, usd, eng)
> Airtime tweaks

- src/components/flow/actions/changegroups/removegroups/RemoveGroupsForm.tsx
- src/components/flow/actions/changegroups/removegroups/__snapshots__/RemoveGroupsForm.test.ts.snap
- src/components/form/assetselector/AssetSelector.tsx
> Exclude dynamic groups from remove from group action

- src/components/simulator/LogEvent.tsx
> Render email_sent events in simulator

- src/components/__snapshots__/index.test.ts.snap
- src/components/form/textinput/TextInputElement.tsx
- src/external/index.ts
- src/flowTypes.ts
- src/store/flowContext.ts
- src/test/config.ts
- src/utils/completion.ts
Add the `@globals` to completion
> Globals completion

- src/components/simulator/LogEvent.module.scss
- src/components/simulator/Simulator.tsx
> Allow messages with only spaces

- src/components/flow/routers/field/FieldRouterForm.module.scss
> Tweak css for split by contact field

- src/components/flow/routers/helpers.test.ts
- src/components/flow/routers/helpers.ts
> Don't modify cases when opening dialog

- src/components/flow/routers/webhook/WebhookRouterForm.tsx
- src/components/flow/routers/webhook/__snapshots__/WebhookRouterForm.test.tsx.snap
- src/components/flow/routers/webhook/helpers.ts
- src/components/nodeeditor/constants.ts
> 💁 Allow customization of body for GET webhooks

- src/components/flow/routers/webhook/WebhookRouterForm.tsx
- src/components/flow/routers/webhook/__snapshots__/WebhookRouterForm.test.tsx.snap
- src/components/flow/routers/webhook/helpers.ts
> More appropriate webhook header defaults

- lambda/flows.js
- src/components/flow/actions/helpers.tsx
- src/components/flow/actions/setrunresult/SetRunResultForm.tsx
- src/components/flow/node/Node.tsx
- src/components/flow/node/helpers.ts
- src/components/flow/routers/subflow/SubflowRouterForm.module.scss
- src/components/flow/routers/subflow/SubflowRouterForm.test.ts
- src/components/flow/routers/subflow/SubflowRouterForm.test.tsx
- src/components/flow/routers/subflow/SubflowRouterForm.tsx
- src/components/flow/routers/subflow/__snapshots__/SubflowRouterForm.test.ts.snap
- src/components/flow/routers/subflow/__snapshots__/SubflowRouterForm.test.tsx.snap
- src/components/flow/routers/subflow/helpers.ts
- src/components/form/assetselector/AssetSelector.test.tsx
- src/config/i18n/defaults.json
- src/global.module.scss
- src/test/utils.tsx
- src/testUtils/assetCreators.ts
- src/utils/index.tsx
At some point in the future it would be nice to give feedback for when these inevitably drift, but as a first go, this feels like a worthwhile feature for heavy subflow users.  @putorti
> Subflow Parameters

- src/components/simulator/ContextExplorer.module.scss
> Align summary text for context explorer

- src/components/simulator/ContextExplorer.test.tsx
- src/components/simulator/ContextExplorer.tsx
- src/components/simulator/__snapshots__/ContextExplorer.test.tsx.snap
- src/components/simulator/helpers.ts
> Fix for missing context explorer values

- src/components/simulator/LogEvent.test.tsx
- src/components/simulator/LogEvent.tsx
- src/components/simulator/__snapshots__/LogEvent.test.tsx.snap
- src/config/i18n/defaults.json
* Render input_labels_added events (#790)
* Fix rendering of contact_groups_changed events (#804)
* Adds tests!
> Simulator event rendering fixes

- src/components/flow/routers/field/helpers.ts
> Tweak operands used in split by contact field routers

- src/components/flow/routers/field/FieldRouterForm.module.scss
- src/components/flow/routers/result/__snapshots__/ResultRouterForm.test.tsx.snap
- src/utils/reactselect.ts
> Tweak split by contact field alignment

- src/components/flow/exit/Exit.tsx
- src/components/flow/node/Node.module.scss
- src/services/Plumber.ts
- src/variables.module.scss
> Fix arrow recalc on connection move

- src/global.module.scss
- src/variables.module.scss
> Bump connectors above nodes on hover

- src/components/flow/routers/helpers.test.ts
- src/components/flow/routers/helpers.ts
- src/setupTests.tsx
- src/testUtils/matchers.ts
> Fix breaking out like-named routes

- src/components/simulator/LogEvent.test.tsx
- src/components/simulator/LogEvent.tsx
- src/components/simulator/__snapshots__/LogEvent.test.tsx.snap
- src/config/i18n/defaults.json
Fixes https://app.intercom.com/a/apps/l6e7tr01/inbox/inbox/conversation/26502859145
> 🧹 Render contact field clearing events in simulator

- package.json
- src/components/canvas/helpers.ts
- src/components/flow/routers/case/CaseElement.module.scss
- src/components/flow/routers/caselist/CaseList.module.scss
- src/components/flow/routers/caselist/CaseList.tsx
- src/components/flow/routers/caselist/__snapshots__/CaseList.test.tsx.snap
- src/components/flow/routers/result/__snapshots__/ResultRouterForm.test.tsx.snap
- src/global.module.scss
- src/index.js
- yarn.lock
* Fixes customElement check for temba-components
* Use temba-components 0.1.5 which has nicer edge styling
* Fix scrollbars for rules, with conditional scrolling treatment
* Fix improper border-radius on rules en-drag when embedded
* Rework use of react-sortable-hoc to address intermittent production runtime issues
> Rule scrolling and edge fixes

- src/utils/index.test.tsx
- src/utils/index.tsx
> Include hyphens in snake chars

- src/components/nodeeditor/NodeEditor.tsx
- src/store/flowContext.ts
- src/store/helpers.ts
- src/store/thunks.ts
Fixes #854 
Issue here is not that it's mixing these issues up, but that there is no treatment for legacy_extra since it is supposed to be filtered out in the editor which was not being done properly.
> Filter out legacy_extra issue properly

- src/components/flow/actions/addurn/__snapshots__/AddURNForm.test.tsx.snap
- src/components/flow/routers/field/__snapshots__/FieldRouterForm.test.ts.snap
- src/components/flow/routers/scheme/__snapshots__/SchemeRouterForm.test.tsx.snap
- src/config/i18n/defaults.json
- src/config/typeConfigs.ts
> Add freshchat scheme option

- src/components/flow/routers/webhook/__snapshots__/WebhookRouterForm.test.tsx.snap
- src/components/flow/routers/webhook/helpers.ts
> 🧵 Add HEAD and PATCH as allowed HTTP methods to match engine

- src/components/translator/TranslatorTab.module.scss
- src/components/translator/TranslatorTab.test.tsx
- src/components/translator/TranslatorTab.tsx
- src/components/translator/__snapshots__/TranslatorTab.test.tsx.snap
- src/config/i18n/defaults.json
- src/flowTypes.ts
- src/test/config.ts
> 🌎 Button to change flow language

- src/components/flow/routers/case/CaseElement.module.scss
- src/components/flow/routers/caselist/CaseList.module.scss
> Don't show drag handle on last rule, tweak single operand width

- package.json
- src/components/form/select/SelectElement.tsx
- src/temba/TembaSelect.tsx
- yarn.lock
> Allow facebook tag selection to be cleared

- src/components/flow/actions/callwebhook/CallWebhook.tsx
- src/components/flow/actions/setrunresult/SetRunResult.tsx
- src/utils/index.tsx
> Truncate save result and webhook text on main edit view

- src/components/flow/actions/sendmsg/SendMsgForm.tsx
- src/external/index.ts
- src/index.js
Adds `httpTimeout` config option. 
Closes #887
> Allow http timeout to be overridden in config

- src/components/flow/routers/case/CaseElement.tsx
- src/components/flow/routers/classify/ClassifyRouterForm.test.tsx
- src/components/flow/routers/classify/ClassifyRouterForm.tsx
- src/components/flow/routers/classify/__snapshots__/ClassifyRouterForm.test.tsx.snap
- src/temba/TembaSelect.tsx
- src/testUtils/assetCreators.ts
Make init match temba-select native objects instead of converting to assets
> Fix missing intents for split by intent

- src/components/flow/Flow.test.ts
- src/components/flow/actions/sendemail/__snapshots__/SendEmailForm.test.ts.snap
- src/components/flow/actions/startsession/__snapshots__/StartSessionForm.test.tsx.snap
- src/components/flow/routers/airtime/__snapshots__/AirtimeRouterForm.test.ts.snap
- src/components/flow/routers/case/__snapshots__/helpers.test.ts.snap
- src/components/flow/routers/classify/helpers.ts
- src/components/flow/routers/response/__snapshots__/ResponseRouterForm.test.ts.snap
- src/components/flow/routers/resthook/__snapshots__/ResthookRouterForm.test.ts.snap
- src/components/flow/routers/webhook/__snapshots__/WebhookRouterForm.test.tsx.snap
- src/config/__snapshots__/operatorConfigs.test.ts.snap
- src/config/__snapshots__/typeConfigs.test.ts.snap
- src/config/helpers.ts
- src/config/interfaces.ts
- src/config/operatorConfigs.ts
- src/config/typeConfigs.ts
- src/external/external.test.ts
- src/external/index.ts
- src/store/__snapshots__/thunks.test.ts.snap
- src/store/helpers.test.ts
- src/store/thunks.test.ts
- src/test/config.ts
Addresses https://github.com/nyaruka/floweditor/issues/628. Might as well make these match for simplicity before we add another one.
Requires tweak on RP side but it's a nice simplification https://github.com/nyaruka/rapidpro/pull/3126
> Use engine flow type names

- src/components/flow/routers/localization/RouterLocalizationForm.tsx
> Fix issue with translating node with has text rule

- src/components/flow/actions/sendemail/__snapshots__/SendEmailForm.test.ts.snap
- src/components/flow/actions/startsession/__snapshots__/StartSessionForm.test.tsx.snap
- src/components/flow/routers/airtime/__snapshots__/AirtimeRouterForm.test.ts.snap
- src/components/flow/routers/classify/__snapshots__/ClassifyRouterForm.test.tsx.snap
- src/components/flow/routers/resthook/__snapshots__/ResthookRouterForm.test.ts.snap
- src/components/flow/routers/ticket/__snapshots__/TicketRouterForm.test.tsx.snap
- src/components/flow/routers/webhook/__snapshots__/WebhookRouterForm.test.tsx.snap
- src/config/__snapshots__/operatorConfigs.test.ts.snap
- src/config/__snapshots__/typeConfigs.test.ts.snap
- src/config/interfaces.ts
Actions like calling classifiers, opening tickets etc
> Allow online actions to be used in background flows

- src/components/flow/actions/updatecontact/UpdateContactForm.test.ts
- src/components/flow/actions/updatecontact/__snapshots__/UpdateContactForm.test.ts.snap
- src/components/flow/actions/updatecontact/helpers.ts
- src/components/flow/routers/ticket/helpers.ts
> Fix open ticket and set channel actions saving full asset to definition instead of reference

- src/components/flow/routers/case/CaseElement.tsx
- src/components/flow/routers/case/helpers.ts
- src/components/form/textinput/helpers.tsx
Fixes: https://github.com/nyaruka/floweditor/issues/965
> Allow expressions in between numeric rules

- src/components/flow/routers/case/CaseElement.tsx
- src/components/flow/routers/caselist/CaseList.test.tsx
- src/components/flow/routers/caselist/CaseList.tsx
- src/components/flow/routers/caselist/__snapshots__/CaseList.test.tsx.snap
Fixes: https://github.com/nyaruka/floweditor/issues/978
> Let the previous operator influence the next empty rule

- src/components/revisions/RevisionExplorer.tsx
- src/flowTypes.ts
- src/store/flowContext.ts
- src/store/thunks.ts
Can be deployed after https://github.com/nyaruka/rapidpro/pull/3292
> Issues is now separate field from flow metadata

- src/components/mediaplayer/MediaPlayer.module.scss
- src/components/mediaplayer/MediaPlayer.tsx
Keep in mind that OGG is not supported by Safari, so if we want to support that in the browser, we need to transcode them on upload.
Fixes #1003
> Fix media player display and loading

- src/components/flow/routers/ticket/TicketRouterForm.tsx
- src/components/flow/routers/ticket/helpers.ts
- src/components/simulator/LogEvent.test.tsx
- src/components/simulator/LogEvent.tsx
* Fix the simulator not showing the ticket subject
> Initialize ticketer properly for the internal only case.

- .gitignore
- src/config/i18n/es/resource.json
- src/config/i18n/fr/resource.json
- src/config/i18n/pt-br/resource.json
(I gave floweditor a config in our fab2 stuff so you can now run `pull-trans` to fetch latest translations from Transifex)
> Include latest translations from transifex

- lambda/topics.js
- lambda/users.js
- package.json
- src/components/__snapshots__/index.test.ts.snap
- src/components/flow/actions/openticket/OpenTicket.tsx
- src/components/flow/routers/ticket/TicketRouterForm.test.tsx
- src/components/flow/routers/ticket/TicketRouterForm.tsx
- src/components/flow/routers/ticket/__snapshots__/TicketRouterForm.test.tsx.snap
- src/components/flow/routers/ticket/helpers.ts
- src/flowTypes.ts
- src/store/validators.ts
- src/temba/TembaSelect.tsx
- src/test/assets/topics.json
- src/test/assets/users.json
- src/test/config.ts
- yarn.lock
> Topic and assignee

- src/components/flow/routers/classify/ClassifyRouterForm.tsx
- src/components/flow/routers/expression/ExpressionRouterForm.tsx
- src/components/flow/routers/expression/__snapshots__/ExpressionRouterForm.test.ts.snap
- src/components/flow/routers/field/FieldRouterForm.tsx
- src/components/flow/routers/field/__snapshots__/FieldRouterForm.test.ts.snap
- src/components/flow/routers/groups/GroupsRouterForm.tsx
- src/components/flow/routers/groups/__snapshots__/GroupsRouterForm.test.ts.snap
- src/components/flow/routers/random/RandomRouterForm.tsx
- src/components/flow/routers/random/__snapshots__/RandomRouterForm.test.tsx.snap
- src/components/flow/routers/response/ResponseRouterForm.tsx
- src/components/flow/routers/result/ResultRouterForm.tsx
- src/components/flow/routers/scheme/SchemeRouterForm.tsx
- src/components/flow/routers/webhook/WebhookRouterForm.tsx
- src/components/form/FormElement.module.scss
> Update validation for various router types

- src/components/simulator/Simulator.tsx
> Ignore empty activity

- src/components/flow/actions/startsession/StartSessionForm.module.scss
- src/components/flow/actions/startsession/StartSessionForm.tsx
- src/components/flow/actions/startsession/__snapshots__/StartSessionForm.test.tsx.snap
> Tweak wording for StartSessionForm using a query

- .github/workflows/build.yml
- package.json
- src/store/thunks.ts
- yarn.lock
* Remove hack for clicking near bottom of action list
> Enable localization of exits with actions

- src/components/flow/routers/airtime/currency/CurrencyElement.tsx
fixes https://github.com/nyaruka/floweditor/issues/986
BEFORE
AFTER
> 🔤 currency dropdown order alpha

- src/store/thunks.ts
> Fix error when deleting a router

- src/components/flow/routers/ticket/TicketRouterForm.tsx
- src/components/flow/routers/ticket/__snapshots__/TicketRouterForm.test.tsx.snap
- src/components/flow/routers/ticket/helpers.ts
- src/config/i18n/defaults.json
- src/config/i18n/es/resource.json
- src/flowTypes.ts
@ericnewcomer how do you feel about getting rid of `@results` as the default?
> Make body optional on open ticket actions

- src/components/flow/routers/ticket/TicketRouterForm.tsx
https://github.com/nyaruka/floweditor/issues/1251
> Disable topic creation

- package.json
- src/components/flow/routers/webhook/WebhookRouterForm.module.scss
- src/components/flow/routers/webhook/WebhookRouterForm.tsx
- src/components/flow/routers/webhook/__snapshots__/WebhookRouterForm.test.tsx.snap
- src/components/form/textinput/TextInputElement.tsx
- src/components/form/textinput/helpers.tsx
- yarn.lock
Use autogrow with max-height on webhook
> Webhook autogrow

- src/components/flow/routers/resthook/__snapshots__/ResthookRouterForm.test.ts.snap
- src/components/flow/routers/resthook/helpers.ts
- src/components/flow/routers/webhook/WebhookRouterForm.test.tsx
- src/components/flow/routers/webhook/__snapshots__/WebhookRouterForm.test.tsx.snap
- src/components/flow/routers/webhook/helpers.ts
> Remove default webhook result name

- src/components/flow/routers/airtime/helpers.ts
- src/components/flow/routers/helpers.ts
- src/components/flow/routers/resthook/helpers.ts
- src/components/flow/routers/ticket/helpers.ts
- src/components/flow/routers/webhook/helpers.ts
@ericnewcomer hoping I can sneak this before your LLM stuff - it helps with that but I'm trying to make ticket splits that don't create results
> Tweak how service call splits are built to allow more flexibility

- src/components/flow/routers/airtime/__snapshots__/AirtimeRouterForm.test.ts.snap
- src/components/flow/routers/airtime/helpers.ts
- src/flowTypes.ts
Requires https://github.com/nyaruka/goflow/pull/1354
> Make result optional and non-default for airtime actions

- package.json
- src/components/flow/actions/addlabels/AddLabelsForm.tsx
- src/components/flow/actions/addlabels/__snapshots__/AddLabelsForm.test.ts.snap
- src/components/flow/actions/addlabels/__snapshots__/AddLabelsForm.test.tsx.snap
- src/components/flow/actions/startsession/StartSessionForm.test.tsx
- src/components/flow/actions/startsession/StartSessionForm.tsx
- src/components/flow/actions/startsession/__snapshots__/StartSessionForm.test.tsx.snap
- src/components/form/assetselector/AssetSelector.tsx
- src/temba/TembaSelect.tsx
- yarn.lock
Remove AssetSelector from:
- AddLabel
- StartSession
> Remove AssetSelector 1

- package.json
- src/components/flow/actions/addlabels/AddLabelsForm.tsx
- src/components/flow/actions/addlabels/__snapshots__/AddLabelsForm.test.ts.snap
- src/components/flow/actions/addlabels/__snapshots__/AddLabelsForm.test.tsx.snap
- src/components/flow/actions/changegroups/addgroups/AddGroupsForm.tsx
- src/components/flow/actions/changegroups/addgroups/__snapshots__/AddGroupsForm.test.ts.snap
- src/components/flow/actions/changegroups/removegroups/RemoveGroupsForm.tsx
- src/components/flow/actions/changegroups/removegroups/__snapshots__/RemoveGroupsForm.test.ts.snap
- src/components/flow/actions/requestoptin/RequestOptInForm.tsx
- src/components/flow/actions/requestoptin/helpers.ts
- src/components/flow/actions/startsession/StartSessionForm.test.tsx
- src/components/flow/actions/startsession/StartSessionForm.tsx
- src/components/flow/actions/startsession/__snapshots__/StartSessionForm.test.tsx.snap
- src/components/form/assetselector/AssetSelector.tsx
- src/temba/TembaSelect.tsx
- yarn.lock
Remove AssetSelector from:
- AddGroup
- RemoveGroup
- RequestOptin
> Remove AssetSelector 2

- src/components/flow/node/helpers.ts
- src/components/flow/routers/airtime/helpers.ts
- src/components/flow/routers/ticket/helpers.ts
- src/flowTypes.ts
- src/store/helpers.test.ts
- src/testUtils/assetCreators.ts
Forgot to clean these up in https://github.com/nyaruka/floweditor/pull/1301
> Remove `OpenTicket.result_name` and `TransferAirtime.result_name` that were removed in spec 14.3

- src/components/flow/routers/airtime/AirtimeRouterForm.tsx
- src/components/flow/routers/airtime/helpers.ts
- src/components/flow/routers/ticket/helpers.ts
- src/components/flow/routers/webhook/WebhookRouterForm.tsx
- src/components/flow/routers/webhook/__snapshots__/WebhookRouterForm.test.tsx.snap
- src/config/i18n/cs/resource.json
- src/config/i18n/defaults.json
- src/config/i18n/es/resource.json
- src/config/i18n/fr/resource.json
- src/config/i18n/mn/resource.json
- src/config/i18n/pt-br/resource.json
* Fix help text examples for webhooks
> Don't prepopulate result names for tickets and airtime

- src/components/simulator/Simulator.tsx
To match https://github.com/nyaruka/goflow/pull/1375
> Update simulator to send msg event as per latest engine changes
