- src/enzymeAdapter.ts
- src/globals.d.ts
This fixes the warnings in vscode for enzyme matchers
> Use jest-enzyme matchers instead of global type defs

- package-lock.json
- package.json
- webpack.common.js
- Enables a level of hot loading for our Sass files, more [here](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/384). 
- Unfortunately, even with this workaround, hot reloading Sass variables is pretty slow. I could be missing something there. 
- I think we should eventually work toward using only `style-loader`/`css-loader`/`sass-loader` to bundle Sass files in development (better support for HMR) and `extract-text-webpack-plugin` in production.
> hot load sass w/ css-hot-loader

- assets/flows/a4f64f1b-85bc-477e-b706-de313a022979.json
- src/component/NodeEditor/NodeEditor.test.tsx
- src/component/NodeEditor/NodeEditor.tsx
- src/component/form/FlowElement.tsx
Fixes nyaruka/floweditor/issues/113
@ycleptkellan could use a hand with the proper way to test `updateSubflowRouter` to ensure it creates the correct exits. Or this presumably is easier with redux?
> Create expiration route when calling out to a flow

- src/component/Exit.tsx
- src/component/Flow.tsx
- src/component/Modal.tsx
- src/component/Node.tsx
- src/component/NodeEditor/NodeEditor.tsx
- src/component/actions/Action/Action.tsx
- src/component/routers/GroupsRouter.tsx
- src/component/routers/SwitchRouter.tsx
- src/flowTypes.ts
- src/services/Plumber.ts
- src/store/actionTypes.ts
- src/store/flowContext.ts
- src/store/flowEditor.ts
- src/store/helpers.ts
- src/store/mutators.ts
- src/store/nodeEditor.ts
- src/store/thunks.ts
Don't want every single object in the flow spec prepended with Temba (this TembaExit, TembaCase, etc), just feels weird. Opted to just rename the one problematic one with a real object collision  to `FlowNode`. Open to bigger rename later if we think it matters.. can revisit.
Fixes: #188
> Rename Node to FlowNode to avoid colliding with dom

- __mocks__/axios.ts
- __test__/assets/config.js
- __test__/assets/contacts.json
- __test__/assets/fields.json
- __test__/assets/flows.json
- __test__/assets/flows/boring.json
- __test__/assets/groups.json
- assets/flows.json
- src/component/Flow.test.ts
- src/component/FlowList.test.ts
- src/component/__snapshots__/FlowList.test.ts.snap
- src/component/actions/Action/Action.test.ts
- src/component/actions/Action/__snapshots__/Action.test.ts.snap
- src/component/index.test.ts
- src/component/routers/GroupsRouter.test.tsx
- src/component/routers/__snapshots__/GroupsRouter.test.tsx.snap
- src/external/index.test.ts
- src/store/__snapshots__/thunks.test.ts.snap
- src/store/flowContext.test.ts
- src/store/flowEditor.test.ts
- src/store/helpers.test.ts
- src/store/helpers.ts
- src/store/mutators.test.ts
- src/store/nodeEditor.test.ts
- src/store/thunks.test.ts
- src/store/thunks.ts
- src/utils/__snapshots__/index.test.tsx.snap
- src/utils/index.test.tsx
Removes references to colors and customer service flows for all of the tests in the store module (and any references to non-test assets). Also refactors a few other tests as an example for use to more toward (`Action.test.ts`, `GroupRouter.test.tsx`, etc).
> Remove more references to non-test assets

- .npmrc
- package-lock.json
- package.json
- webpack/webpack.umd.js
This PR ensures we're doing the right thing by unpkg (as a scoped package) when building the `umd` distribution folder. These changes were used to publish the [latest version of the package](https://unpkg.com/@nyaruka/flow-editor@1.1.2/). Running the `npm version patch` command bumped us two patch versions for some reason 🤷‍♂️. I'll look into a publishing tool/process so that we can prevent that sort of thing from happening in the future.
> Rework package scoping

- src/component/Modal.scss
Modal footer needs `display: flex;` to keep buttons vertically centered when timeout control isn't present.
> Fix footer style

- src/component/form/AttribElement.test.tsx
- src/component/form/AttribElement.tsx
- src/component/form/GroupsElement.test.ts
- src/component/form/GroupsElement.tsx
- src/component/form/__snapshots__/GroupsElement.test.ts.snap
- src/utils/index.test.tsx
- src/utils/index.tsx
- Solves the issue we were running into w/ `AttribElement` whereby whitespace wasn't 
being stripped from the value passed to the `createNewOption` handler.
- Extracts common handlers `isOptionUnique`, `isValidNewOption`, and `optionExists` out to utils.
> Apply isOptionUnique callback to GroupsElement

- src/component/Exit.scss
- src/component/Exit.tsx
- src/component/SelectSearch/SelectSearch.test.ts
- src/component/SelectSearch/SelectSearch.tsx
- src/component/SelectSearch/SelectValue.tsx
- src/component/SelectSearch/__snapshots__/SelectSearch.test.ts.snap
- src/component/SelectSearch/helper.tsx
- src/component/actions/Action/Action.scss
- src/component/actions/Action/Action.tsx
- src/component/actions/StartFlow/StartFlow.test.ts
- src/component/actions/StartFlow/StartFlow.tsx
- src/component/actions/StartFlow/__snapshots__/StartFlow.test.ts.snap
- src/component/actions/helpers.tsx
- src/component/form/AttribElement.test.tsx
- src/component/form/AttribElement.tsx
- src/component/form/FlowElement.tsx
- src/store/thunks.ts
* Fix stray 'x' on single select widgets
* Fix missing styling on start flow action
* Render start flow with shared asset list renderer
* Fix switching to a split when there is no previous node
> Small rendering fixes

- src/component/Flow.test.ts
- src/component/Flow.tsx
- src/component/Modal.tsx
- src/component/Node.tsx
- src/component/NodeEditor/NodeEditor.test.ts
- src/component/NodeEditor/NodeEditor.tsx
- src/component/actions/Action/Action.test.ts
- src/component/actions/Action/Action.tsx
- src/component/form/CaseElement.scss
- src/component/form/CaseElement.tsx
- src/component/routers/GroupsRouter.test.tsx
- src/component/routers/GroupsRouter.tsx
- src/component/routers/SwitchRouter.test.tsx
- src/component/routers/SwitchRouter.tsx
- src/store/actionTypes.ts
- src/store/index.ts
- src/store/nodeEditor.test.ts
- src/store/nodeEditor.ts
- src/store/thunks.test.ts
- src/store/thunks.ts
This is mostly housekeeping to prepare for a uniform form model for nodes and actions. It pretty much is just moving `nodeToEdit` and `actionToEdit` to be part of `NodeEditorSettings`. The goal being that the bits needed to construct the forms (on load and type change but are otherwise static) will live there. Also removes associated redux actions and reducers.
Current thinking is that eventually `nodeEditor` will be comprised of `settings` and `form`. The remaining things will be pushed into one or the other.
> Move nodeToEdit and actionToEdit

- preview/config.js
- src/components/flow/Flow.tsx
- src/components/flow/node/Node.scss
- src/components/flow/node/Node.tsx
- src/config/ConfigProvider.tsx
- src/flowTypes.ts
- src/index.ts
- src/store/__snapshots__/thunks.test.ts.snap
- src/store/editor.ts
- src/testUtils/index.tsx
- src/utils/debug.ts
Added state object to implement debugging features. Implemented first debug option which shows an overlay on each node with their uuid and copies it to the clipboard when clicked.
To try it, open the console and type:
`> window.fe.showUUIDs()`
> Debug Options

- package-lock.json
- package.json
- src/components/flow/routers/caselist/__snapshots__/CaseList.test.ts.snap
- src/components/form/textinput/TextInputElement.scss
- src/components/form/textinput/TextInputElement.tsx
- src/components/simulator/Simulator.tsx
- src/variables.scss
* Functions floating at the bottom
* Render function details as markdown
* Tab the same as enter for functions
* Complete both parens for no-arg functions
* Fixes: #519 
* Fixes: #521
> Completion updates

- src/components/fixy/Fixy.tsx
- src/components/flow/actions/setrunresult/SetRunResultForm.test.ts
- src/components/flow/actions/setrunresult/SetRunResultForm.tsx
- src/components/flow/actions/setrunresult/__snapshots__/SetRunResultForm.test.ts.snap
- src/components/flow/actions/setrunresult/helpers.ts
- src/components/form/assetselector/AssetSelector.tsx
Use AssetSelector when naming flow results to make it easier to reuse result names.
Fixes: #516
> Set Result Asset Selector

- src/components/flow/actions/sendbroadcast/__snapshots__/SendBroadcastForm.test.ts.snap
- src/components/flow/actions/startsession/__snapshots__/StartSessionForm.test.ts.snap
- src/components/flow/actions/updatecontact/UpdateContact.tsx
- src/components/flow/actions/updatecontact/UpdateContactForm.tsx
- src/components/flow/actions/updatecontact/__snapshots__/UpdateContactForm.test.ts.snap
- src/components/flow/actions/updatecontact/helpers.ts
- src/components/flow/node/Node.tsx
- src/testUtils/assetCreators.ts
* Use org language name if present
* Exclude default/base from set language options
Fixes: #646 
Note: if definitions contain languages that are not in the org, a language code will be shown instead
> Changes to set language

- src/components/flow/actions/localization/MsgLocalizationForm.test.ts
- src/components/flow/actions/localization/MsgLocalizationForm.tsx
- src/components/flow/actions/localization/__snapshots__/MsgLocalizationForm.test.ts.snap
- src/components/flow/actions/sendmsg/SendMsg.module.scss
Also shows translated quick replies in gray instead of red.
Fixes: #660
> Don't save empty quick reply lists on localization

- src/components/flow/node/Node.tsx
- src/components/flow/routers/expression/helpers.ts
- src/components/flow/routers/field/helpers.ts
- src/components/flow/routers/groups/helpers.ts
- src/components/flow/routers/localization/helpers.ts
- src/components/flow/routers/random/helpers.ts
- src/components/flow/routers/response/helpers.ts
- src/components/flow/routers/result/helpers.ts
- src/components/flow/routers/subflow/helpers.ts
- src/components/flow/routers/wait/helpers.ts
- src/components/flow/routers/webhook/helpers.ts
- src/config/typeConfigs.ts
- src/store/helpers.ts
* Use `@(urn_parts(urns.tel).path)` when saving scheme splits
* Fallback to split by expression for unnamed schemes
Fixes: #676
> Split by phone

- src/components/flow/routers/case/CaseElement.tsx
Pre-populates the confidence when an intent is configured. Note this isn't straight up default since we don't want validation to kick in until something has been entered.
Fixes: #728
> Default confidence to .9 when selecting an intent

- src/components/flow/Flow.tsx
> Don't scroll canvas when dialog is open

- src/components/simulator/LogEvent.module.scss
- src/components/simulator/LogEvent.tsx
- src/config/i18n/defaults.json
> Disambiguate simulator email i18n key

- src/components/flow/routers/webhook/WebhookRouterForm.test.tsx
- src/components/flow/routers/webhook/WebhookRouterForm.tsx
- src/store/validators.ts
> Add conditional validation for urls

- src/components/simulator/LogEvent.tsx
> Don't show html encoded info messages

- src/components/flow/actions/addlabels/AddLabel.test.ts
- src/components/flow/actions/addlabels/AddLabels.tsx
- src/components/flow/actions/addlabels/__snapshots__/AddLabel.test.ts.snap
- src/components/flow/actions/addurn/AddURN.tsx
- src/components/flow/actions/changegroups/ChangeGroups.test.ts
- src/components/flow/actions/changegroups/ChangeGroups.tsx
- src/components/flow/actions/changegroups/__snapshots__/ChangeGroups.test.ts.snap
- src/components/flow/actions/changegroups/__snapshots__/helpers.test.ts.snap
- src/components/flow/actions/changegroups/addgroups/__snapshots__/AddGroupsForm.test.ts.snap
- src/components/flow/actions/changegroups/removegroups/__snapshots__/RemoveGroupsForm.test.ts.snap
- src/components/flow/actions/helpers.tsx
- src/components/flow/actions/sendbroadcast/SendBroadcast.test.ts
- src/components/flow/actions/sendbroadcast/SendBroadcast.tsx
- src/components/flow/actions/sendbroadcast/__snapshots__/SendBroadcast.test.ts.snap
- src/components/flow/actions/startsession/StartSession.test.tsx
- src/components/flow/actions/startsession/StartSession.tsx
- src/components/flow/actions/startsession/__snapshots__/StartSession.test.tsx.snap
- src/components/flow/routers/groups/__snapshots__/GroupsRouterForm.test.ts.snap
- src/test/assets/groups.json
Adds `+n more` for any over 5 instead of `...`
Fixes: #775
> Elide at 5 for asset lists

- src/components/flow/actions/addurn/AddURN.tsx
- src/components/flow/actions/addurn/__snapshots__/AddURN.test.tsx.snap
- src/components/flow/actions/setrunresult/SetRunResult.test.ts
- src/components/flow/actions/setrunresult/SetRunResult.tsx
- src/components/flow/actions/setrunresult/__snapshots__/SetRunResult.test.ts.snap
Addresses #736. Not sure what the rules are.. but seems value should always be emphasized. It's more noticeable in RP than the preview where the bolding is slight.
> Tweak styling of value in AddURN and SetRunResult to match UpdateContact

- src/components/flow/actions/sendmsg/SendMsgForm.tsx
- src/components/form/textinput/ExcellentParser.ts
- src/components/form/textinput/TextInputElement.test.ts
- src/utils/completion.ts
- Uppercase matching for functions
- Hide completion when drilling into webhooks
- Don't validate for missing fields if the expression is a webhook
Fixes: #807 
Fixes: #812 
Fixes: #813
> Completion fixes

- package.json
- src/components/flow/exit/Exit.module.scss
- src/components/flow/exit/Exit.test.ts
- src/components/flow/exit/Exit.tsx
- src/components/flow/exit/__snapshots__/Exit.test.ts.snap
- src/components/simulator/Simulator.tsx
- src/external/index.ts
- src/store/editor.ts
- yarn.lock
~16k bundle hit to leverage moment so these can be localizable.
Fixes: #784
> Switch to relative dates on recent messages

- src/components/flow/routers/case/__snapshots__/CaseElement.test.tsx.snap
- src/components/flow/routers/caselist/__snapshots__/CaseList.test.tsx.snap
- src/components/flow/routers/result/__snapshots__/ResultRouterForm.test.tsx.snap
- src/config/__snapshots__/operatorConfigs.test.ts.snap
- src/config/operatorConfigs.ts
Fixes: #725 
Removes has_value (Not Empty) rule from list for new nodes, but allows existing nodes that use it to continue to do so.
> Hide has_value for new nodes

- src/components/flow/Flow.tsx
- src/config/i18n/defaults.json
- src/external/index.ts
- src/store/thunks.ts
Tries to address possibility of stale implicit saving and save lockout. Also adds a separate monitor to check for stale changes.
> Saving Improvements

- src/components/__snapshots__/index.test.ts.snap
- src/components/canvas/Canvas.module.scss
- src/components/canvas/Canvas.test.tsx
- src/components/canvas/Canvas.tsx
- src/components/canvas/CanvasDraggable.tsx
- src/components/canvas/__snapshots__/Canvas.test.tsx.snap
- src/components/flow/Flow.module.scss
- src/components/flow/Flow.test.ts
- src/components/flow/Flow.tsx
- src/components/flow/__snapshots__/Flow.test.ts.snap
- src/components/flow/node/Node.test.tsx
- src/components/flow/node/Node.tsx
- src/components/index.module.scss
- src/components/index.tsx
- src/components/languageselector/LanguageSelector.module.scss
- src/global.module.scss
- src/services/Plumber.ts
- src/store/__snapshots__/thunks.test.ts.snap
- src/store/editor.ts
- src/store/helpers.ts
- src/utils/index.tsx
Significantly reworks canvas structure in order to support horizontal scrolling. Pushes drag node down to canvas so it can work with native offsets (removing a 2x render cost on load).  Traced and removed more unnecessary (hopefully!) updates for better performance on large flows. Debounce re-anchoring connections on drag so it is smoother on large flows.
> More performance updates, add horizontal scrolling

- src/components/flow/routers/field/FieldRouterForm.test.ts
- src/components/flow/routers/field/FieldRouterForm.tsx
- src/components/flow/routers/field/__snapshots__/FieldRouterForm.test.ts.snap
- src/components/flow/routers/field/helpers.ts
Fields selected via the asset selector are field objects now, but the expression builder wasn't accounting for that. This also adds a test for expressions created from field operands.
> Field route fix

- src/components/flow/routers/classify/ClassifyRouterForm.test.tsx
- src/components/flow/routers/classify/__snapshots__/ClassifyRouterForm.test.tsx.snap
- src/components/flow/routers/classify/helpers.ts
Use the result name if it is set when editing split by intent nodes
> Intent result name

- src/components/flow/routers/airtime/AirtimeRouterForm.tsx
- src/components/flow/routers/airtime/__snapshots__/AirtimeRouterForm.test.ts.snap
- src/components/flow/routers/airtime/currency/CurrencyElement.module.scss
- src/components/flow/routers/airtime/currency/CurrencyElement.tsx
- src/components/form/assetselector/AssetSelector.tsx
- src/components/form/textinput/TextInputElement.module.scss
- src/components/form/textinput/TextInputElement.tsx
This was broken with the `AssetSelector` switch. `AirtimeRouterForm` did not pass down an `Assets` object (instead building the currency objects itself). Now that `CurrencyElement` uses an `AssetSelector` under the hood, it can just send the `Assets` object for currencies.
> CurrencyElement fix

- src/components/flow/actions/sendmsg/SendMsgForm.tsx
- src/components/flow/routers/case/__snapshots__/CaseElement.test.tsx.snap
- src/components/flow/routers/case/__snapshots__/helpers.test.ts.snap
- src/components/flow/routers/caselist/CaseList.tsx
- src/components/flow/routers/caselist/__snapshots__/CaseList.test.tsx.snap
- src/components/flow/routers/caselist/helpers.ts
- src/components/flow/routers/classify/ClassifyRouterForm.tsx
- src/components/flow/routers/classify/helpers.ts
- src/components/flow/routers/digits/DigitsRouterForm.tsx
- src/components/flow/routers/digits/__snapshots__/DigitsRouterForm.test.ts.snap
- src/components/flow/routers/result/__snapshots__/ResultRouterForm.test.tsx.snap
- src/config/__snapshots__/operatorConfigs.test.ts.snap
- src/config/operatorConfigs.ts
* Allow text rules in ivr flows in all splits but the digit router
* Fixes issue making sure the default rule is not one that has been filtered out.
Also snuck in.. 
fixes: https://github.com/rapidpro/rapidpro/issues/1432
> Only restrict rules on digits router for ivr flows

- src/components/simulator/LogEvent.tsx
- src/components/simulator/Simulator.tsx
Trying to get rid of wait objects on sessions because it's just duplication of what is in the wait event. Mailroom doesn't use them.
> Simulator should use wait events rather than the wait object

- src/components/canvas/Canvas.tsx
The containing page can register for the `temba-node-selection-changed` event:
```javascript
document.addEventListener("temba-node-selection-changed", function(event){
console.log(event.detail);
});
```
Which would yield something like this:
```javascript
{
"nodes": {
"1bb35e73-f635-42b1-b9c9-0b7798c936e9": {left: 340, top: 40, right: 1177, bottom: 148},
"2bc3f025-8d5e-47b3-9ac8-0ef3aef66d42": {left: 380, top: 220, right: 588, bottom: 367},
"5bbb1209-b12e-4353-9823-1fb5715ed288": {left: 40, top: 0, right: 248, bottom: 294},
}
}
```
Closes #1017
> Fire event when node selection changes

- src/components/flow/routers/localization/RouterLocalizationForm.tsx
8 total rules, 6 numeric rules, 2 non-numeric -> only the 2 non-numeric rules display in the rule translations tab list
AFTER 1/3
AFTER 2/3
AFTER 3/3
> excluding all date, time, and numeric rules from translations

- src/components/translator/TranslatorTab.tsx
- src/flowTypes.ts
- src/store/helpers.ts
- src/store/mutators.test.ts
- src/store/mutators.ts
- src/store/thunks.ts
* Skip single character and numeric translation requests
* Handle ai.reasoning errors
* Keep record of which attributes have been auto translated for each node
> Auto translation updates

- src/components/flow/routers/airtime/__snapshots__/AirtimeRouterForm.test.ts.snap
- src/components/flow/routers/airtime/helpers.ts
- src/components/flow/routers/helpers.ts
- src/components/flow/routers/resthook/__snapshots__/ResthookRouterForm.test.ts.snap
- src/components/flow/routers/resthook/helpers.ts
- src/components/flow/routers/ticket/__snapshots__/TicketRouterForm.test.tsx.snap
- src/components/flow/routers/ticket/helpers.ts
- src/components/flow/routers/webhook/__snapshots__/WebhookRouterForm.test.tsx.snap
- src/components/flow/routers/webhook/helpers.ts
- src/flowTypes.ts
- src/testUtils/assetCreators.ts
Part 1 of https://github.com/nyaruka/floweditor/issues/1273
> Rework webhook nodes to route on @webhook.status
